default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: myuser
  password: mypassword
  pool: 5

development:
  <<: *default
  database: mydatabase

test:
  <<: *default
  database: mydatabase_test

production:
  <<: *default
  database: mydatabase_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
